services:
  app:
    image: jeankhawand/anki-sync-server:24.04.1
    container_name: anki-sync-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SYNC_USER1=${USER1}
    volumes:
      - anki_data:/home/anki

volumes:
  anki_data:
